var earthquake_count = {
    "China": 362,
    "Indonesia": 291,
    "Japan": 241,
    "Iran": 219,
    "Usa": 192,
    "Turkey": 168,
    "Italy": 133,
    "Philippines": 129,
    "Russia": 119,
    "Peru": 118,
    "Chile": 113,
    "Mexico": 107,
    "Greece": 106,
    "Papua New Guinea": 90,
    "Taiwan": 75,
    "India": 74,
    "Solomon Islands": 61,
    "Colombia": 54,
    "Afghanistan": 51,
    "New Zealand": 51,
    "Vanuatu": 47,
    "Pakistan": 45,
    "Ecuador": 41,
    "Algeria": 38,
    "Nicaragua": 30,
    "Venezuela": 28,
    "Guatemala": 28,
    "Albania": 27,
    "Myanmar (Burma)": 27,
    "Costa Rica": 26,
    "Tajikistan": 24,
    "El Salvador": 23,
    "Usa Territory": 22,
    "Australia": 20,
    "Tonga": 19,
    "Panama": 19,
    "New Caledonia": 19,
    "Kermadec Islands (New Zealand)": 17,
    "Fiji": 17,
    "Argentina": 16,
    "Canada": 15,
    "South Africa": 13,
    "Bulgaria": 12,
    "Bangladesh": 12,
    "France": 12,
    "Nepal": 11,
    "Kyrgyzstan": 11,
    "Azores (Portugal)": 11,
    "Romania": 10,
    "Serbia": 10,
    "Bosnia-Herzegovina": 9,
    "Iceland": 8,
    "Spain": 8,
    "Georgia": 8,
    "Honduras": 8,
    "Slovenia": 8,
    "Dominican Republic": 8,
    "Samoa": 8,
    "Croatia": 8,
    "Uzbekistan": 7,
    "Azerbaijan": 7,
    "Kazakhstan": 7,
    "Ethiopia": 7,
    "Macedonia": 7,
    "Uk": 6,
    "Egypt": 6,
    "Tanzania": 6,
    "Brazil": 6,
    "Mongolia": 6,
    "Morocco": 6,
    "Poland": 6,
    "Congo": 5,
    "Armenia": 5,
    "Atlantic Ocean": 5,
    "South Georgia And The South Sandwich Islands": 5,
    "Germany": 5,
    "Montenegro": 5,
    "Bhutan": 5,
    "Bolivia": 5,
    "Cuba": 4,
    "Rwanda": 4,
    "Guadeloupe": 4,
    "Trinidad And Tobago": 4,
    "Haiti": 4,
    "Tunisia": 4,
    "Micronesia, Fed. States Of": 4,
    "Turkmenistan": 4,
    "Malawi": 4,
    "Antarctica": 4,
    "Malaysia": 3,
    "Thailand": 3,
    "Yemen": 3,
    "Sudan": 3,
    "South Korea": 3,
    "Uganda": 3,
    "Hungary": 3,
    "Saudi Arabia": 3,
    "Ukraine": 3,
    "Mozambique": 3,
    "Netherlands": 3,
    "Indian Ocean": 3,
    "Cyprus": 2,
    "Cameroon": 2,
    "Zambia": 2,
    "Martinique": 2,
    "Israel": 2,
    "Pacific Ocean": 2,
    "Lebanon": 2,
    "Jamaica": 2,
    "Kenya": 2,
    "Vietnam": 2,
    "Ghana": 2,
    "Portugal": 2,
    "Uk Territory": 1,
    "Antigua And Barbuda": 1,
    "Togo": 1,
    "Belgium": 1,
    "Syria": 1,
    "Switzerland": 1,
    "Solomon Sea": 1,
    "Austria": 1,
    "Slovakia": 1,
    "Saint Lucia": 1,
    "Wallis And Futuna (French Territory)": 1,
    "Djibouti": 1,
    "Bering Sea": 1,
    "Palau": 1,
    "Czech Republic": 1,
    "Madagascar": 1,
    "Libya": 1,
    "Burundi": 1,
    "Kiribati": 1,
    "Central African Republic": 1,
    "Jordan": 1,
    "Comoros": 1,
    "Iraq": 1,
    "Guinea": 1,
    "Gabon": 1,
    "Laos": 1
  };
