var earthquake_count_by_country = [
  {key:"China",value:362,group:"East Asia"},
  {key:"Indonesia",value:291,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Japan",value:241,group:"East Asia"},
  {key:"Iran",value:219,group:"Middle East"},
  {key:"Usa",value:192,group:"North America and Hawaii"},
  {key:"Turkey",value:168,group:"Middle East"},
  {key:"Italy",value:133,group:"Southern Europe"},
  {key:"Philippines",value:129,group:"Central and South Pacific"},
  {key:"Russia",value:119,group:"Kamchatka and Kuril Islands"},
  {key:"Peru",value:118,group:"South America"},
  {key:"Chile",value:113,group:"South America"},
  {key:"Mexico",value:107,group:"North America and Hawaii"},
  {key:"Greece",value:106,group:"Southern Europe"},
  {key:"Papua New Guinea",value:90,group:"Central and South Pacific"},
  {key:"Taiwan",value:75,group:"East Asia"},
  {key:"India",value:74,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Solomon Islands",value:61,group:"Central and South Pacific"},
  {key:"Colombia",value:54,group:"South America"},
  {key:"Afghanistan",value:51,group:"Central Asia and Caucasus"},
  {key:"New Zealand",value:51,group:"Central and South Pacific"},
  {key:"Vanuatu",value:47,group:"Central and South Pacific"},
  {key:"Pakistan",value:45,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Ecuador",value:41,group:"South America"},
  {key:"Algeria",value:38,group:"Northern Africa"},
  {key:"Nicaragua",value:30,group:"Central America"},
  {key:"Venezuela",value:28,group:"Caribbean"},
  {key:"Guatemala",value:28,group:"Central America"},
  {key:"Albania",value:27,group:"Southern Europe"},
  {key:"Myanmar (Burma)",value:27,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Costa Rica",value:26,group:"Central America"},
  {key:"Tajikistan",value:24,group:"Central Asia and Caucasus"},
  {key:"El Salvador",value:23,group:"Central America"},
  {key:"Usa Territory",value:22,group:"Caribbean"},
  {key:"Australia",value:20,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Tonga",value:19,group:"Central and South Pacific"},
  {key:"New Caledonia",value:19,group:"Central and South Pacific"},
  {key:"Panama",value:19,group:"Central America"},
  {key:"Fiji",value:17,group:"Central and South Pacific"},
  {key:"Kermadec Islands (New Zealand)",value:17,group:"Central and South Pacific"},
  {key:"Argentina",value:16,group:"South America"},
  {key:"Canada",value:15,group:"North America and Hawaii"},
  {key:"South Africa",value:13,group:"Central, Western and S. Africa"},
  {key:"France",value:12,group:"Northern and Western Europe"},
  {key:"Bulgaria",value:12,group:"Eastern Europe"},
  {key:"Bangladesh",value:12,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Azores (Portugal)",value:11,group:"Southern Europe"},
  {key:"Kyrgyzstan",value:11,group:"Central Asia and Caucasus"},
  {key:"Nepal",value:11,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Serbia",value:10,group:"Southern Europe"},
  {key:"Romania",value:10,group:"Eastern Europe"},
  {key:"Bosnia-Herzegovina",value:9,group:"Southern Europe"},
  {key:"Slovenia",value:8,group:"Southern Europe"},
  {key:"Spain",value:8,group:"Southern Europe"},
  {key:"Honduras",value:8,group:"Caribbean"},
  {key:"Iceland",value:8,group:"Northern and Western Europe"},
  {key:"Croatia",value:8,group:"Southern Europe"},
  {key:"Samoa",value:8,group:"Central and South Pacific"},
  {key:"Dominican Republic",value:8,group:"Caribbean"},
  {key:"Georgia",value:8,group:"Central Asia and Caucasus"},
  {key:"Azerbaijan",value:7,group:"Central Asia and Caucasus"},
  {key:"Uzbekistan",value:7,group:"Central Asia and Caucasus"},
  {key:"Macedonia",value:7,group:"Southern Europe"},
  {key:"Kazakhstan",value:7,group:"Central Asia and Caucasus"},
  {key:"Ethiopia",value:7,group:"Central, Western and S. Africa"},
  {key:"Morocco",value:6,group:"Northern Africa"},
  {key:"Brazil",value:6,group:"South America"},
  {key:"Tanzania",value:6,group:"Central, Western and S. Africa"},
  {key:"Uk",value:6,group:"Northern and Western Europe"},
  {key:"Egypt",value:6,group:"Northern Africa"},
  {key:"Poland",value:6,group:"Northern and Western Europe"},
  {key:"Mongolia",value:6,group:"Central Asia and Caucasus"},
  {key:"Montenegro",value:5,group:"Southern Europe"},
  {key:"Congo",value:5,group:"Central, Western and S. Africa"},
  {key:"Atlantic Ocean",value:5,group:"Atlantic Ocean"},
  {key:"Germany",value:5,group:"Northern and Western Europe"},
  {key:"Armenia",value:5,group:"Central Asia and Caucasus"},
  {key:"Bolivia",value:5,group:"South America"},
  {key:"Bhutan",value:5,group:"S. and SE. Asia and Indian Ocean"},
  {key:"South Georgia And The South Sandwich Islands",value:5,group:"Atlantic Ocean"},
  {key:"Antarctica",value:4,group:"Antarctica"},
  {key:"Rwanda",value:4,group:"Central, Western and S. Africa"},
  {key:"Cuba",value:4,group:"Caribbean"},
  {key:"Micronesia",value:4,group:"Central and South Pacific"},
  {key:"Tunisia",value:4,group:"Northern Africa"},
  {key:"Haiti",value:4,group:"Caribbean"},
  {key:"Turkmenistan",value:4,group:"Central Asia and Caucasus"},
  {key:"Malawi",value:4,group:"Central, Western and S. Africa"},
  {key:"Trinidad And Tobago",value:4,group:"Caribbean"},
  {key:"Guadeloupe",value:4,group:"Caribbean"},
  {key:"Mozambique",value:3,group:"Central, Western and S. Africa"},
  {key:"Hungary",value:3,group:"Eastern Europe"},
  {key:"Yemen",value:3,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Thailand",value:3,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Sudan",value:3,group:"Northern Africa"},
  {key:"Indian Ocean",value:3,group:"S. and SE. Asia and Indian Ocean"},
  {key:"South Korea",value:3,group:"East Asia"},
  {key:"Malaysia",value:3,group:"Central and South Pacific"},
  {key:"Ukraine",value:3,group:"Eastern Europe"},
  {key:"Uganda",value:3,group:"Central, Western and S. Africa"},
  {key:"Netherlands",value:3,group:"Northern and Western Europe"},
  {key:"Saudi Arabia",value:3,group:"Middle East"},
  {key:"Vietnam",value:2,group:"East Asia"},
  {key:"Zambia",value:2,group:"Central, Western and S. Africa"},
  {key:"Cameroon",value:2,group:"Central, Western and S. Africa"},
  {key:"Kenya",value:2,group:"Central, Western and S. Africa"},
  {key:"Ghana",value:2,group:"Central, Western and S. Africa"},
  {key:"Cyprus",value:2,group:"Southern Europe"},
  {key:"Pacific Ocean",value:2,group:"Central and South Pacific"},
  {key:"Portugal",value:2,group:"Southern Europe"},
  {key:"Martinique",value:2,group:"Caribbean"},
  {key:"Israel",value:2,group:"Middle East"},
  {key:"Lebanon",value:2,group:"Middle East"},
  {key:"Jamaica",value:2,group:"Caribbean"},
  {key:"Uk Territory",value:1,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Comoros",value:1,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Saint Lucia",value:1,group:"Caribbean"},
  {key:"Central African Republic",value:1,group:"Central, Western and S. Africa"},
  {key:"Djibouti",value:1,group:"Central, Western and S. Africa"},
  {key:"Burundi",value:1,group:"Central, Western and S. Africa"},
  {key:"Bering Sea",value:1,group:"Bering Sea"},
  {key:"Belgium",value:1,group:"Northern and Western Europe"},
  {key:"Austria",value:1,group:"Northern and Western Europe"},
  {key:"Wallis And Futuna (French Territory)",value:1,group:"Central and South Pacific"},
  {key:"Antigua And Barbuda",value:1,group:"Caribbean"},
  {key:"Czech Republic",value:1,group:"Eastern Europe"},
  {key:"Iraq",value:1,group:"Middle East"},
  {key:"Gabon",value:1,group:"Central, Western and S. Africa"},
  {key:"Guinea",value:1,group:"Central, Western and S. Africa"},
  {key:"Togo",value:1,group:"Central, Western and S. Africa"},
  {key:"Jordan",value:1,group:"Middle East"},
  {key:"Syria",value:1,group:"Middle East"},
  {key:"Switzerland",value:1,group:"Northern and Western Europe"},
  {key:"Kiribati",value:1,group:"Central and South Pacific"},
  {key:"Libya",value:1,group:"Northern Africa"},
  {key:"Madagascar",value:1,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Solomon Sea",value:1,group:"Central and South Pacific"},
  {key:"Palau",value:1,group:"Central and South Pacific"},
  {key:"Slovakia",value:1,group:"Eastern Europe"},
  {key:"Laos",value:1,group:"S. and SE. Asia and Indian Ocean"}
  ];

earthquake_count_by_region = [
  {key:"Central and South Pacific",value:620,group:"Central and South Pacific"},
  {key:"East Asia",value:602,group:"East Asia"},
  {key:"Middle East",value:397,group:"Middle East"},
  {key:"South America",value:367,group:"South America"},
  {key:"S. and SE. Asia and Indian Ocean",value:363,group:"S. and SE. Asia and Indian Ocean"},
  {key:"Southern Europe",value:335,group:"Southern Europe"},
  {key:"North America and Hawaii",value:313,group:"North America and Hawaii"},
  {key:"Central Asia and Caucasus",value:229,group:"Central Asia and Caucasus"},
  {key:"Central America",value:128,group:"Central America"},
  {key:"Kamchatka and Kuril Islands",value:102,group:"Kamchatka and Kuril Islands"},
  {key:"Caribbean",value:59,group:"Caribbean"},
  {key:"Northern Africa",value:58,group:"Northern Africa"},
  {key:"Central, Western and S. Africa",value:58,group:"Central, Western and S. Africa"},
  {key:"Northern and Western Europe",value:43,group:"Northern and Western Europe"},
  {key:"Eastern Europe",value:30,group:"Eastern Europe"},
  {key:"Atlantic Ocean",value:11,group:"Atlantic Ocean"},
  {key:"Antarctica",value:4,group:"Antarctica"},
  {key:"Bering Sea",value:1,group:"Bering Sea"}
]
